id: A49413E2B
base_file: fAB3F.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:47:38.556740
  last_modified_at: 2022-05-30 21:47:38.556747
